name: Deploy FastAPI Lambda

on:
  push:
    branches:
      - main  # Cambia si quieres otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Cambia si tu Lambda usa otra versión

    - name: Install zip utility
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir package
        pip install --target ./package -r requirements.txt

    - name: Package Lambda
      run: |
        cd package
        zip -r ../deployment-package.zip .
        cd ..
        zip -g deployment-package.zip -r app main.py config.py

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia si tu Lambda está en otra región

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name radarapi-lambda \
          --zip-file fileb://deployment-package.zip
